export const pokemonFetchRequestActionTypes = (() => {
  return {
    POKEMON_FETCH_REQUEST: 'POKEMON_FETCH_REQUEST',
    POKEMON_FETCH_SUCCESS: 'POKEMON_FETCH_SUCCESS',
    POKEMON_FETCH_FAILURE: 'POKEMON_FETCH_FAILURE'
  }
})();